### PR TITLE
Feature/cli

### PR DESCRIPTION
**Pull request by jurra**
Hi @girgink here is the cli with all the commands we discussed to implement. Please give it a try and see.

I saw you deleted utils.py, and some other scripts, I find useful the code there specially when testing. if you think there is a better place to place this one let me know, I would prefer not to just get rid of it.

If you have other suggestions let me know as well here and I can implement them in this branch.

One issue that is worth noticing, it is not possible at the moment to delete a dataset in figshare using the url. It is also not possible to get this url from the web interface. One way around this could be to get the id, from the url and then delete it using id...... but is not very elegant or scalable.

### CODE REVIEW

**Comment by jurra** [comment]
Another concern I have is the size of the repository, perhaps because of this continuous commiting of the cassettes which can be quite big files. I think we should find a smart way to downsize the repository, perhaps the best one is to just have the master branch and delete branches when things are working and integrated.

**Comment by girgink** [comment]
> Another concern I have is the size of the repository, perhaps because of this continuous commiting of the cassettes which can be quite big files.

I honestly think that cassettes should not be part of the repository. These are assets that can be generated on demand, there is no need to have them. I suggest we delete them completely.

**Comment by jurra** [comment]
What I understand is that the cassettes should be stored in the test environment, the only way to use them and meet the requirement of not having it in the source code, is to store them somewhere else and copy them to the github actions environment. Another possibility is to make the cassettes as light as possible or having the main branch without them, and the dev branch with the cassettes for example.

The other (simplistic) option is not using them at all, but I think this will just make testing much more slower.

**Comment by manuGil** [comment]
@girgink @jurra  I think we need to merge this before the workshop. I suggest we take the easiest approach to integrate a working version of the CLI for the package. We can discuss the best approaches for the issues raised here later. I am afraid we won't have enough time to address them properly on time.

- Would it be possible to exclude the cassettes from the CLI for now if the concern about the size of the repo is critical? 
- I work on reviewing the rest and resolve the conflicts

**Comment by manuGil** [comment]
I will review this pull request and ignore the cassettes for now. Later, we can find a solution.

**Comment by manuGil** [comment]
I can't get the tests running. I will leave them for now and come back to them later

```python
FAILED tests/test_fairly.py::test_create_and_upload_dataset[client0] - ValueError: No access token
FAILED tests/test_fairly.py::test_create_and_upload_dataset[client1] - ValueError: No access token
FAILED tests/test_fairly.py::test_download_dataset[client0] - ValueError: No access token
FAILED tests/test_fairly.py::test_download_dataset[client1] - ValueError: No access token
FAILED tests/test_fairly.py::test_get_account_datasets[client0] - vcr.errors.CannotOverwriteExistingCassetteException: Can't overwrite existing cassette ('tests/fixtures/vcr_cassettes/test_get_account_datasets[client0].yaml') ...
FAILED tests/test_fairly.py::test_get_account_datasets[client1] - vcr.errors.CannotOverwriteExistingCassetteException: Can't overwrite existing cassette ('tests/fixtures/vcr_cassettes/test_get_account_datasets[client1].yaml') ...
ERROR tests/test_cli.py::test_dataset_clone - ValueError: No access token
```

**Comment by manuGil** [comment]
The CLI feature was added by PR #24

**Pull request closed without merging**
